### ISSUE TITLE
Listeners cannot be found for created deployments.

### ISSUE THREAD

**Issue by caleblayneheath** [Aria-Deploy/Aria#12]
Aria deployment can be successfully created (shows up in AWS), however is not acknowledged by Aria itself.

Production environment is the [Aria Demo Stack](https://github.com/Aria-Deploy/Aria-Demo-Production).
```
true
undefined
true
undefined
The following error occured when trying to fetch profile stacks:  ListenerNotFound: One or more listeners not found
    at deserializeAws_queryDescribeRulesCommandError (/home/clh/ariaTest/Aria/server/node_modules/@aws-sdk/client-elastic-load-balancing-v2/dist-cjs/protocols/Aws_query.js:1736:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/clh/ariaTest/Aria/server/node_modules/@aws-sdk/client-elastic-load-balancing-v2/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at /home/clh/ariaTest/Aria/server/node_modules/@aws-sdk/client-elastic-load-balancing-v2/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at StandardRetryStrategy.retry (/home/clh/ariaTest/Aria/server/node_modules/@aws-sdk/client-elastic-load-balancing-v2/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at /home/clh/ariaTest/Aria/server/node_modules/@aws-sdk/client-elastic-load-balancing-v2/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at /home/clh/ariaTest/Aria/server/src/cfn_interface/lib/aws_cfn_data.ts:226:27
    at async Promise.all (index 2)
    at Object.fetchStacksInfo (/home/clh/ariaTest/Aria/server/src/cfn_interface/lib/aws_cfn_data.ts:197:29) {
  Type: 'Sender',
  Code: 'ListenerNotFound',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'fadf8238-325a-4685-a301-10c0c94963cc',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

**Comment by caleblayneheath** [comment]
Closed as false alarm. Mea maxima culpa. Was working with version some commits behind.
